version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres
    ports:
      - "5432:5432"
  application:
    container_name: app
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
    - postgres