spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres


database:
  tables:
    people: soa_people
    workers: soa_workers
    orgs: soa_orgs